spring:
  datasource:
    url: jdbc:h2:mem:testdb # default value on UI is: jdbc:h2:~/test. But when it writes to file, H2 does not execute data.sql.
    # this prop is the default values of h2-console textbox. do not change.
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081
  servlet:
    context-path: /orm-demo

logging.level.org.hibernate: TRACE
